/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLedgerRouteImport } from './routes/_authenticated/ledger'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedContributionsIndexRouteImport } from './routes/_authenticated/contributions.index'
import { Route as AuthenticatedContributionsContributionIdRouteImport } from './routes/_authenticated/contributions.$contributionId'
import { Route as AuthenticatedDuesIndexRouteImport } from './routes/_authenticated/dues.index'
import { Route as AuthenticatedDuesDueIdRouteImport } from './routes/_authenticated/dues.$dueId'
import { Route as AuthenticatedMembersIndexRouteImport } from './routes/_authenticated/members.index'
import { Route as AuthenticatedMembersMemberIdRouteImport } from './routes/_authenticated/members.$memberId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLedgerRoute = AuthenticatedLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContributionsIndexRoute =
  AuthenticatedContributionsIndexRouteImport.update({
    id: '/contributions/',
    path: '/contributions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContributionsContributionIdRoute =
  AuthenticatedContributionsContributionIdRouteImport.update({
    id: '/contributions/$contributionId',
    path: '/contributions/$contributionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDuesIndexRoute = AuthenticatedDuesIndexRouteImport.update({
  id: '/dues/',
  path: '/dues/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDuesDueIdRoute = AuthenticatedDuesDueIdRouteImport.update({
  id: '/dues/$dueId',
  path: '/dues/$dueId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersIndexRoute =
  AuthenticatedMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersMemberIdRoute =
  AuthenticatedMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/contributions/$contributionId': typeof AuthenticatedContributionsContributionIdRoute
  '/dues/$dueId': typeof AuthenticatedDuesDueIdRoute
  '/members/$memberId': typeof AuthenticatedMembersMemberIdRoute
  '/contributions/': typeof AuthenticatedContributionsIndexRoute
  '/dues/': typeof AuthenticatedDuesIndexRoute
  '/members/': typeof AuthenticatedMembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/contributions/$contributionId': typeof AuthenticatedContributionsContributionIdRoute
  '/dues/$dueId': typeof AuthenticatedDuesDueIdRoute
  '/members/$memberId': typeof AuthenticatedMembersMemberIdRoute
  '/contributions': typeof AuthenticatedContributionsIndexRoute
  '/dues': typeof AuthenticatedDuesIndexRoute
  '/members': typeof AuthenticatedMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ledger': typeof AuthenticatedLedgerRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/contributions/$contributionId': typeof AuthenticatedContributionsContributionIdRoute
  '/_authenticated/dues/$dueId': typeof AuthenticatedDuesDueIdRoute
  '/_authenticated/members/$memberId': typeof AuthenticatedMembersMemberIdRoute
  '/_authenticated/contributions/': typeof AuthenticatedContributionsIndexRoute
  '/_authenticated/dues/': typeof AuthenticatedDuesIndexRoute
  '/_authenticated/members/': typeof AuthenticatedMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/ledger'
    | '/reports'
    | '/settings'
    | '/contributions/$contributionId'
    | '/dues/$dueId'
    | '/members/$memberId'
    | '/contributions/'
    | '/dues/'
    | '/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/ledger'
    | '/reports'
    | '/settings'
    | '/contributions/$contributionId'
    | '/dues/$dueId'
    | '/members/$memberId'
    | '/contributions'
    | '/dues'
    | '/members'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/ledger'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/contributions/$contributionId'
    | '/_authenticated/dues/$dueId'
    | '/_authenticated/members/$memberId'
    | '/_authenticated/contributions/'
    | '/_authenticated/dues/'
    | '/_authenticated/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ledger': {
      id: '/_authenticated/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AuthenticatedLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contributions/': {
      id: '/_authenticated/contributions/'
      path: '/contributions'
      fullPath: '/contributions/'
      preLoaderRoute: typeof AuthenticatedContributionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contributions/$contributionId': {
      id: '/_authenticated/contributions/$contributionId'
      path: '/contributions/$contributionId'
      fullPath: '/contributions/$contributionId'
      preLoaderRoute: typeof AuthenticatedContributionsContributionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dues/': {
      id: '/_authenticated/dues/'
      path: '/dues'
      fullPath: '/dues/'
      preLoaderRoute: typeof AuthenticatedDuesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dues/$dueId': {
      id: '/_authenticated/dues/$dueId'
      path: '/dues/$dueId'
      fullPath: '/dues/$dueId'
      preLoaderRoute: typeof AuthenticatedDuesDueIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/': {
      id: '/_authenticated/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthenticatedMembersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/$memberId': {
      id: '/_authenticated/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof AuthenticatedMembersMemberIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLedgerRoute: typeof AuthenticatedLedgerRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedContributionsContributionIdRoute: typeof AuthenticatedContributionsContributionIdRoute
  AuthenticatedDuesDueIdRoute: typeof AuthenticatedDuesDueIdRoute
  AuthenticatedMembersMemberIdRoute: typeof AuthenticatedMembersMemberIdRoute
  AuthenticatedContributionsIndexRoute: typeof AuthenticatedContributionsIndexRoute
  AuthenticatedDuesIndexRoute: typeof AuthenticatedDuesIndexRoute
  AuthenticatedMembersIndexRoute: typeof AuthenticatedMembersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLedgerRoute: AuthenticatedLedgerRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedContributionsContributionIdRoute:
    AuthenticatedContributionsContributionIdRoute,
  AuthenticatedDuesDueIdRoute: AuthenticatedDuesDueIdRoute,
  AuthenticatedMembersMemberIdRoute: AuthenticatedMembersMemberIdRoute,
  AuthenticatedContributionsIndexRoute: AuthenticatedContributionsIndexRoute,
  AuthenticatedDuesIndexRoute: AuthenticatedDuesIndexRoute,
  AuthenticatedMembersIndexRoute: AuthenticatedMembersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
