-- TOTALS IN THE DATABASE
-- Every money figure the app shows now comes from these functions instead of being
-- added up in the browser. That fixes silent truncation at 1,000 rows and makes the
-- dashboard, reports and member profile agree.
--
-- All functions are SECURITY INVOKER: they run as the signed-in user, so the existing
-- row-level security keeps each organization's data separate.
--
-- _periods: the dues periods to look at, keyed by frequency, current period first:
--   {"monthly": [{"label": "Sep 2026", "ends_on": "2026-09-30"}, ...], "custom": [{"label": "All time", "ends_on": null}], ...}
-- Period labels are still generated by the app (src/lib/periods.ts); this argument goes
-- away when periods are stored as dates.

-- ---------------------------------------------------------------------------
-- The one place that decides who owes what.
--   Dues: every active due, for each period in _periods that ended on or after the day
--         the due was created. Short = amount - paid (never negative). A past period
--         that is short adds the due's late charge.
--   Contributions: only compulsory ones, only for the members picked for them.
--         Freewill contributions are never owed.
--   Members: active members, or the one member asked for (so an inactive member's
--         profile still shows what they owe).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.standing_lines(_periods jsonb, _member_id uuid DEFAULT NULL)
RETURNS TABLE (
  kind text,            -- 'due' or 'contribution'
  member_id uuid,
  ref_id uuid,          -- due id or contribution id
  ref_name text,
  period_label text,    -- null for contributions
  is_current boolean,   -- current period (dues) or still open (contributions)
  is_past boolean,      -- a due period that has already ended
  expected numeric,
  paid numeric,
  short numeric,
  penalty numeric
)
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  WITH m AS (
    SELECT id FROM members
    WHERE org_id = current_org_id()
      AND ((_member_id IS NULL AND active) OR id = _member_id)
  ),
  d AS (
    SELECT id, name, amount, frequency, penalty_amount, created_at
    FROM dues
    WHERE org_id = current_org_id() AND active
  ),
  p AS (
    SELECT d.id AS due_id, e.val ->> 'label' AS label, (e.val ->> 'ends_on')::date AS ends_on, e.ord
    FROM d
    CROSS JOIN LATERAL jsonb_array_elements(coalesce(_periods -> d.frequency::text, '[]'::jsonb))
      WITH ORDINALITY AS e(val, ord)
  ),
  p_in AS (
    SELECT p.* FROM p JOIN d ON d.id = p.due_id
    WHERE p.ends_on IS NULL OR p.ends_on >= (d.created_at AT TIME ZONE 'Africa/Lagos')::date
  ),
  dp AS (
    SELECT due_id, member_id, period_label, sum(amount) AS paid
    FROM due_payments
    WHERE org_id = current_org_id() AND (_member_id IS NULL OR member_id = _member_id)
    GROUP BY due_id, member_id, period_label
  ),
  cp AS (
    SELECT contribution_id, member_id, sum(amount) AS paid
    FROM contribution_payments
    WHERE org_id = current_org_id() AND (_member_id IS NULL OR member_id = _member_id)
    GROUP BY contribution_id, member_id
  )
  SELECT
    'due',
    m.id,
    d.id,
    d.name,
    p_in.label,
    p_in.ord = 1,
    p_in.ord > 1 AND p_in.ends_on IS NOT NULL,
    d.amount,
    coalesce(dp.paid, 0),
    greatest(d.amount - coalesce(dp.paid, 0), 0),
    CASE WHEN p_in.ord > 1 AND p_in.ends_on IS NOT NULL AND d.amount > coalesce(dp.paid, 0)
         THEN d.penalty_amount ELSE 0 END
  FROM d
  JOIN p_in ON p_in.due_id = d.id
  CROSS JOIN m
  LEFT JOIN dp ON dp.due_id = d.id AND dp.member_id = m.id AND dp.period_label = p_in.label
  UNION ALL
  SELECT
    'contribution',
    cm.member_id,
    c.id,
    c.name,
    NULL,
    NOT c.closed,
    false,
    c.amount_per_person,
    coalesce(cp.paid, 0),
    greatest(c.amount_per_person - coalesce(cp.paid, 0), 0),
    0
  FROM contribution_members cm
  JOIN contributions c ON c.id = cm.contribution_id AND c.mandatory
  JOIN m ON m.id = cm.member_id
  LEFT JOIN cp ON cp.contribution_id = c.id AND cp.member_id = cm.member_id
  WHERE c.org_id = current_org_id()
$$;

-- What each member owes in total.
CREATE OR REPLACE FUNCTION public.member_balances(_periods jsonb, _member_id uuid DEFAULT NULL)
RETURNS TABLE (
  member_id uuid,
  name text,
  dues_owing numeric,
  penalties numeric,
  contributions_owing numeric,
  total_owing numeric
)
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  SELECT
    m.id,
    m.name,
    coalesce(sum(l.short) FILTER (WHERE l.kind = 'due'), 0),
    coalesce(sum(l.penalty), 0),
    coalesce(sum(l.short) FILTER (WHERE l.kind = 'contribution'), 0),
    coalesce(sum(l.short + l.penalty), 0)
  FROM members m
  LEFT JOIN standing_lines(_periods, _member_id) l ON l.member_id = m.id
  WHERE m.org_id = current_org_id()
    AND ((_member_id IS NULL AND m.active) OR m.id = _member_id)
  GROUP BY m.id, m.name
$$;

-- Money in and out, cash and bank, optionally for a date range.
CREATE OR REPLACE FUNCTION public.ledger_totals(_from date DEFAULT NULL, _to date DEFAULT NULL)
RETURNS jsonb
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  SELECT jsonb_build_object(
    'income',       coalesce(sum(amount) FILTER (WHERE kind = 'income'), 0),
    'expense',      coalesce(sum(amount) FILTER (WHERE kind = 'expense'), 0),
    'balance',      coalesce(sum(CASE WHEN kind = 'income' THEN amount ELSE -amount END), 0),
    'cash_in',      coalesce(sum(amount) FILTER (WHERE kind = 'income' AND method = 'cash'), 0),
    'transfer_in',  coalesce(sum(amount) FILTER (WHERE kind = 'income' AND method = 'transfer'), 0),
    'cash_out',     coalesce(sum(amount) FILTER (WHERE kind = 'expense' AND method = 'cash'), 0),
    'transfer_out', coalesce(sum(amount) FILTER (WHERE kind = 'expense' AND method = 'transfer'), 0),
    'cash',         coalesce(sum(CASE WHEN kind = 'income' THEN amount ELSE -amount END) FILTER (WHERE method = 'cash'), 0),
    'bank',         coalesce(sum(CASE WHEN kind = 'income' THEN amount ELSE -amount END) FILTER (WHERE method = 'transfer'), 0)
  )
  FROM ledger_entries
  WHERE org_id = current_org_id()
    AND (_from IS NULL OR entry_date >= _from)
    AND (_to IS NULL OR entry_date <= _to)
$$;

-- Per-contribution progress. A picked member counts as paid once their payments reach
-- the amount per person (or, when there is no set amount, once they have given anything).
CREATE OR REPLACE FUNCTION public.contribution_progress(_open_only boolean DEFAULT false)
RETURNS jsonb
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  WITH c AS (
    SELECT id, name, amount_per_person, target_amount, due_date, closed, created_at
    FROM contributions
    WHERE org_id = current_org_id() AND (NOT _open_only OR NOT closed)
  ),
  per_member AS (
    SELECT contribution_id, member_id, sum(amount) AS paid
    FROM contribution_payments
    WHERE org_id = current_org_id()
    GROUP BY contribution_id, member_id
  ),
  stats AS (
    SELECT
      c.id,
      (SELECT count(*) FROM contribution_members cm WHERE cm.contribution_id = c.id) AS picked,
      (SELECT count(*) FROM contribution_members cm
         JOIN per_member pm ON pm.contribution_id = cm.contribution_id AND pm.member_id = cm.member_id
         WHERE cm.contribution_id = c.id
           AND CASE WHEN c.amount_per_person > 0 THEN pm.paid >= c.amount_per_person ELSE pm.paid > 0 END
      ) AS paid_people,
      (SELECT coalesce(sum(paid), 0) FROM per_member pm WHERE pm.contribution_id = c.id) AS collected
    FROM c
  )
  SELECT coalesce(jsonb_agg(jsonb_build_object(
      'id', c.id,
      'name', c.name,
      'closed', c.closed,
      'due_date', c.due_date,
      'picked', s.picked,
      'paid_people', s.paid_people,
      'collected', s.collected,
      'target', coalesce(nullif(c.target_amount, 0), s.picked * c.amount_per_person)
    ) ORDER BY c.closed, c.due_date NULLS LAST, c.created_at DESC), '[]'::jsonb)
  FROM c JOIN stats s ON s.id = c.id
$$;

-- Everything the dashboard shows, in one call.
CREATE OR REPLACE FUNCTION public.dashboard_summary(_periods jsonb)
RETURNS jsonb
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  WITH lines AS (SELECT * FROM standing_lines(_periods)),
  cur AS (SELECT * FROM lines WHERE kind = 'due' AND is_current)
  SELECT ledger_totals() || jsonb_build_object(
    'owed', (SELECT coalesce(sum(short + penalty), 0) FROM lines),
    'member_count', (SELECT count(*) FROM members WHERE org_id = current_org_id() AND active),
    'dues_paid', (SELECT count(*) FROM cur WHERE paid >= expected),
    'dues_unpaid', (SELECT count(*) FROM cur WHERE paid < expected),
    'contributions', contribution_progress(true),
    'recent', (
      SELECT coalesce(jsonb_agg(to_jsonb(r) ORDER BY r.entry_date DESC, r.created_at DESC), '[]'::jsonb)
      FROM (
        SELECT id, kind, label, description, amount, entry_date, created_at
        FROM ledger_entries
        WHERE org_id = current_org_id()
        ORDER BY entry_date DESC, created_at DESC
        LIMIT 6
      ) r
    )
  )
$$;

-- Everything the reports page shows, in one call.
CREATE OR REPLACE FUNCTION public.report_summary(_from date, _to date, _periods jsonb)
RETURNS jsonb
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  SELECT ledger_totals(_from, _to) || jsonb_build_object(
    'by_label', (
      SELECT coalesce(jsonb_agg(jsonb_build_object('label', label, 'income', income, 'expense', expense)
                                ORDER BY income DESC, expense DESC), '[]'::jsonb)
      FROM (
        SELECT label,
               coalesce(sum(amount) FILTER (WHERE kind = 'income'), 0) AS income,
               coalesce(sum(amount) FILTER (WHERE kind = 'expense'), 0) AS expense
        FROM ledger_entries
        WHERE org_id = current_org_id() AND entry_date BETWEEN _from AND _to
        GROUP BY label
      ) t
    ),
    'defaulters', (
      SELECT coalesce(jsonb_agg(jsonb_build_object('id', member_id, 'name', name, 'owing', total_owing)
                                ORDER BY total_owing DESC, name), '[]'::jsonb)
      FROM member_balances(_periods)
      WHERE total_owing > 0
    ),
    'contributions', contribution_progress(false)
  )
$$;

REVOKE ALL ON FUNCTION public.standing_lines(jsonb, uuid) FROM anon, public;
REVOKE ALL ON FUNCTION public.member_balances(jsonb, uuid) FROM anon, public;
REVOKE ALL ON FUNCTION public.ledger_totals(date, date) FROM anon, public;
REVOKE ALL ON FUNCTION public.contribution_progress(boolean) FROM anon, public;
REVOKE ALL ON FUNCTION public.dashboard_summary(jsonb) FROM anon, public;
REVOKE ALL ON FUNCTION public.report_summary(date, date, jsonb) FROM anon, public;

GRANT EXECUTE ON FUNCTION public.standing_lines(jsonb, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.member_balances(jsonb, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ledger_totals(date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.contribution_progress(boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.dashboard_summary(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.report_summary(date, date, jsonb) TO authenticated;
